;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Item.Stat.UsesLeft",DevComment="")
+GameplayTagList=(Tag="Status",DevComment="")
+GameplayTagList=(Tag="Status.Busy",DevComment="")
+GameplayTagList=(Tag="Status.Busy.Attacking",DevComment="")
+GameplayTagList=(Tag="Status.Busy.Dodging",DevComment="")
+GameplayTagList=(Tag="Status.Busy.Interacting",DevComment="")
+GameplayTagList=(Tag="Status.Busy.Running",DevComment="")
+GameplayTagList=(Tag="Status.Busy.UsingItem",DevComment="")
+GameplayTagList=(Tag="Status.CameraLocked",DevComment="")

